export const trackedProperties = {
  veiculosPage: 'Veículos',
  limitesPage: 'Limites',
  dashboardPage: 'Dashboard',
  pedidosPage: 'Pedidos',
  contatosPage: 'Contatos',
  ofertasPage: 'Ofertas',
  concessionariasPage: 'Concessionarias',
  gruposPage: 'Grupos',
  emailsPage: 'Emails',
  historicoPage: 'Historico',
  analistasPage: 'Analistas',
  gerentesPage: 'Gerentes',
  alertasPage: 'Alertas',
  descontosPage: 'Descontos',
  condicoesPage: 'Condições',
  comunicadosPage: 'Comunicados',

  editarVeiculo: 'Editar Veículo',
  inserirVeiculo: 'Inserir Veículo',
  editarModelo: 'Editar Modelo',
  inserirModelo: 'Inserir Modelo',
  editarAlerta: 'Editar Alerta',
  inserirAlerta: 'Inserir Alerta',
  updatePedido: 'Update Pedido',
  editarContato: 'Editar Contato',
  inserirContato: 'Inserir Contato',
  updateConcessionaria: 'Update Concessionaria',
  inserirGrupo: 'Inserir Grupo',
  inserirAnalista: 'Inserir Analista',
  inserirGerente: 'Inserir Gerente',
  inserirDesconto: 'Inserir Desconro',
  editarDesconto: 'Editar Desconto',
  inserirCondicao: 'Inserir Condicao',
  editarCondicao: 'Editar Condicao',
  historicoTaxas: 'Historico Taxas',
  cadastroTaxas: 'Cadastro taxas',
};

export default trackedProperties;
