export const statusLimitesMap = {
  'Liberar para dealer': 'Liberar para dealer',
  aguardando_aprovacao_dealer: 'Aguardando aceite dealer',
  aprovacao_aceita_dealer: 'Aprovação aceita dealer',
  aprovacao_recusada_dealer: 'Aprovação recusada dealer',
  aprovacao_retida: 'Aprovação retida',
  aprovacao_pausada: 'Aprovação pausada',
  aprovacao_cancelada: 'Aprovação cancelada',
  enviado_para_cadastro: 'Enviado para cadastro',
  atualizar_documentos_dealer: 'Atualizar documentos dealer',
  documentos_atualizados_dealer: 'Documentos atualizados dealer',
  documentos_cadastrais_analise: 'Cadastro em análise',
  cadastro_atualizado: 'Cadastro atualizado',
  renovacao_cadastral: 'Em renovação cadastral',
  enviado_para_juridico: 'Enviado para jurídico',
  aguardando_assinatura_dealer: 'Aguardando assinatura dealer',
  contrato_assinado_digitalizado: 'Contrato assinado digitalizado',
  contratos_analise: 'Contratos em análise',
  contrato_digitalizado_validado: 'Contrato digitalizado validado',
  contrato_fisico_recebido: 'Contrato recebido',
  enviado_para_credito: 'Enviado para crédito',
  obs_do_credito: 'Observações do crédito',
  limite_implantado: 'Limite implantado',
  pendente_documentos: 'Pendente docs. dealer',
  documentos_enviados_parcialmente: 'Docs. enviados parcialmente',
  Pendente: 'Cancelado no Sisgar',
  analise_financiamento_rede: 'Análise financiamento rede',
  docs_juridico_atualizado_dealer: 'Docs. jurídico atualizados dealer',
  docs_juridico_enviados_parcialmente: 'Docs. jurídico enviados parcialmente',
  pendente_docs_juridico_dealer: 'Pendente docs. jurídico dealer',
  pendente_docs_formalizar_dealer: 'Pendente docs. para formalizar dealer',
  pendente_docs_original_dealer: 'Pendente docs. original dealer',
  docs_somente_para_formalizar: 'Docs. somente para formalizar',
  docs_formalizar_enviados_sem_retorno: 'Docs. para formalizar enviados - sem retorno',
  docs_formalizar_atualizado_dealer: 'Docs. para formalizar atualizado dealer',
  docs_formalizar_enviados_parcialmente: 'Docs. para formalizar enviados parcialmente',
  atualizacao_docs_juridico: 'Em atualização docs. jurídico',
  assinatura_docusign: 'Assinatura Docusign',
  aprovacao_finalizada: 'Aprovação finalizada',
  analise_juridico: 'Análise jurídico',
  pendente_docs_complementares_dealer: 'Pendente Docs. complementares dealer',
  docs_somente_formalizar: 'Docs. somente para formalizar',
  docusing_docs_formalizar_sem_retorno: 'Docusign e Docs. formalizar sem retorno',
  reativada_sisgar: 'Aprovação reativada no Sisgar',
};

export const statusPedidosMap = {
  financiamento_reversao: 'Financiamento reversão',
  analise_credito: 'Aguardando análise de crédito',
  financiamento_finalizacao: 'Aguardando contato com cliente para cancelamento',
  financiamento_analise: 'Aguardando revisão',
  separacao: 'Em separação',
  pronto_para_faturamento: 'Pronto para faturamento',
  faturado: 'Faturado',
  finalizado: 'Finalizado por reprovação de crédito',
  cancelado: 'Cancelado',
  cancelado_pelo_cliente: 'Pedido cancelado pelo cliente',
  analise_comercial: 'Aguardando análise comercial',
  analise_comercial_reprovada: 'Análise comercial reprovada',
  contrato_anexado: 'Contrato anexado',
  contrato_pago: 'Contrato pago',
  contrato_cancelado: 'Contrato cancelado',
  cancelado_ordem: 'Cancelado (ordem)',
};
